In [25]:
import pandas as pd
import requests
from datetime import datetime

# Connect with API
base_url = "https://data.cityofnewyork.us/api/v3/views/k46n-sa2m/query.json?pageNumber=1&pageSize=2000&app_token=wlEqLX8cddLmKefHSpYZ8qgbK"
response = requests.get(base_url)

# Set up our columns via lists
date = []
total_adults = []
total_children = []
total_individuals = []
single_men = []
single_women = []
total_single_adults = []
families_with_children = []
adults_in_families = []
children = []
total_individuals_families = []
adult_families = []
individuals_adult_familes = []

# If status code is valid, append the values into the lists above and convert them into columns
if response.status_code == 200:
    dhs_data = response.json()
    for row in dhs_data:
        total_adults.append(int(row["total_adults_in_shelter"]))
        # Specific edits for date to get only year, month, day and convert from string to date
        date.append(datetime.fromisoformat(row["date_of_census"][0:10]))
        total_children.append(int(row["total_children_in_shelter"]))
        total_individuals.append(int(row["total_individuals_in_shelter"]))
        single_men.append(int(row["single_adult_men_in_shelter"]))
        single_women.append(int(row["single_adult_women_in_shelter"]))
        families_with_children.append(int(row["families_with_children_in_shelter"]))
else:
    print("ERROR")

# Create dataframe, set up columns and print
df = pd.DataFrame({"Date": date, "Adults": total_adults, "Single Men": single_men, "Single Women": single_women, "Children": total_children, "Families": families_with_children, "Individuals": total_individuals})
df

,Date,Adults,Single Men,Single Women,Children,Families,Individuals
0,2021-03-01,35195,13936,4543,16746,9593,51941
1,2021-03-02,35202,13962,4526,16746,9590,51948
2,2021-03-03,35108,13931,4503,16720,9579,51828
3,2021-03-04,35176,13989,4526,16720,9578,51896
4,2021-03-05,35103,13939,4485,16766,9598,51869
...,...,...,...,...,...,...,...
1899,2026-05-13,54626,18268,7211,28367,16447,82993
1900,2026-05-14,54536,18221,7209,28341,16432,82877
1901,2026-05-15,54425,18137,7189,28326,16423,82751
1902,2026-05-16,54388,18034,7195,28400,16474,82788
1903,2026-05-17,54473,18047,7209,28450,16510,82923

In [26]:
df[df["Date"] >= "2026-1-1"]

,Date,Adults,Single Men,Single Women,Children,Families,Individuals
1767,2026-01-01,55640,17724,6875,30649,17624,86289
1768,2026-01-02,55697,17741,6893,30677,17645,86374
1769,2026-01-03,55721,17774,6891,30632,17625,86353
1770,2026-01-04,55731,17804,6922,30590,17600,86321
1771,2026-01-05,55767,17824,6938,30581,17591,86348
...,...,...,...,...,...,...,...
1899,2026-05-13,54626,18268,7211,28367,16447,82993
1900,2026-05-14,54536,18221,7209,28341,16432,82877
1901,2026-05-15,54425,18137,7189,28326,16423,82751
1902,2026-05-16,54388,18034,7195,28400,16474,82788
1903,2026-05-17,54473,18047,7209,28450,16510,82923