In [ ]:
import pandas as pd
import requests
from datetime import datetime

# Connect with API
base_url = "https://data.cityofnewyork.us/api/v3/views/k46n-sa2m/query.json?pageNumber=1&pageSize=2000&app_token=wlEqLX8cddLmKefHSpYZ8qgbK"
response = requests.get(base_url)

# Set up our columns via lists
date = []
total_adults = []
total_children = []
total_individuals = []
single_men = []
single_women = []
total_single_adults = []
families_with_children = []
adults_in_families = []
children = []
total_individuals_families = []
adult_families = []
individuals_adult_familes = []

# If status code is valid, append the values into the lists above and convert them into columns
if response.status_code == 200:
    dhs_data = response.json()
    for row in dhs_data:
        total_adults.append(int(row["total_adults_in_shelter"]))

        # Specific edits for date to get only year, month, day and convert from string to date
        date.append(pd.to_datetime(row["date_of_census"][0:10]))
        
        total_children.append(int(row["total_children_in_shelter"]))
        total_individuals.append(int(row["total_individuals_in_shelter"]))
        single_men.append(int(row["single_adult_men_in_shelter"]))
        single_women.append(int(row["single_adult_women_in_shelter"]))
        families_with_children.append(int(row["families_with_children_in_shelter"]))
else:
    print("ERROR")

# Create dataframe, set up columns and print
df = pd.DataFrame({"Date": date, "Adults": total_adults, "Single Men": single_men, "Single Women": single_women, "Children": total_children, "Families": families_with_children, "Individuals": total_individuals})
df_adults = df[["Date", "Adults"]]
df_adults

           Date  Adults
0    2021-03-01   35195
1    2021-03-02   35202
2    2021-03-03   35108
3    2021-03-04   35176
4    2021-03-05   35103
...         ...     ...
1906 2026-05-20   54345
1907 2026-05-21   54430
1908 2026-05-22   54472
1909 2026-05-23   54522
1910 2026-05-24   54465

[1911 rows x 2 columns]

In [17]:
# Testing if dates work
# df[df["Date"] >= "2026-1-1"]
# df[df["Date"] > "2025"]
# print(type(df["Date"][1]))
test = df[df["Date"].between("2021-12-1", "2022-1")]
test

,Date,Adults,Single Men,Single Women,Children,Families,Individuals
275,2021-12-01,31063,12583,4154,14760,8498,45823
276,2021-12-02,30944,12510,4150,14727,8496,45671
277,2021-12-03,30872,12449,4140,14725,8484,45597
278,2021-12-04,30901,12459,4120,14787,8512,45688
279,2021-12-05,30943,12466,4137,14802,8516,45745
280,2021-12-06,30991,12534,4146,14787,8498,45778
281,2021-12-07,31007,12545,4169,14773,8500,45780
282,2021-12-08,31054,12595,4157,14782,8507,45836
283,2021-12-09,31015,12536,4156,14816,8529,45831
284,2021-12-10,30991,12456,4125,14908,8581,45899
285,2021-12-11,30910,12445,4094,14855,8560,45765
286,2021-12-12,31071,12556,4131,14855,8559,45926
287,2021-12-13,31084,12546,4153,14861,8553,45945
288,2021-12-14,31040,12558,4150,14830,8547,45870
289,2021-12-15,30949,12558,4138,14735,8501,45684
290,2021-12-16,30965,12566,4112,14756,8513,45721
291,2021-12-17,30839,12450,4083,14773,8526,45612
292,2021-12-18,30853,12482,4086,14772,8520,45625
293,2021-12-19,30926,12561,4090,14737,8511,45663
294,2021-12-20,30931,12561,4127,14665,8463,45596
295,2021-12-21,30933,12536,4128,14685,8480,45618
296,2021-12-22,30811,12529,4128,14579,8407,45390
297,2021-12-23,30897,12534,4133,14674,8467,45571
298,2021-12-24,30741,12410,4112,14658,8460,45399
299,2021-12-25,30696,12368,4064,14705,8482,45401
300,2021-12-26,30786,12504,4070,14659,8460,45445
301,2021-12-27,30788,12536,4079,14576,8413,45364
302,2021-12-28,30665,12481,4098,14574,8384,45239
303,2021-12-29,30687,12497,4062,14612,8413,45299
304,2021-12-30,30644,12444,4057,14601,8417,45245
305,2021-12-31,30400,12269,3978,14596,8430,44996
306,2022-01-01,30554,12354,3993,14659,8455,45213

In [13]:
# Grouped by year and month, then created dataframe for maximum value per unique month/year in each column
grouped_df = df.groupby([df['Date'].dt.year, df['Date'].dt.month]).max()

# Vall sp
grouped_adults = grouped_df[["Date", "Adults"]]
grouped_adults

                Date  Adults
Date Date
2021 3    2021-03-31   35232
     4    2021-04-30   34471
     5    2021-05-31   33638
     6    2021-06-30   32826
     7    2021-07-31   31326
     8    2021-08-31   30813
     9    2021-09-30   30827
     10   2021-10-31   31220
     11   2021-11-30   31285
     12   2021-12-31   31084
2022 1    2022-01-31   30872
     2    2022-02-28   30828
     3    2022-03-31   30802
     4    2022-04-30   30943
     5    2022-05-31   31095
     6    2022-06-30   31755
     7    2022-07-31   33270
     8    2022-08-31   35712
     9    2022-09-30   40327
     10   2022-10-31   43176
     11   2022-11-30   43277
     12   2022-12-31   44613
2023 1    2023-01-31   47572
     2    2023-02-28   47980
     3    2023-03-31   49269
     4    2023-04-30   51776
     5    2023-05-31   54505
     6    2023-06-30   54236
     7    2023-07-31   53977
     8    2023-08-31   54065
     9    2023-09-30   53584
     10   2023-10-31   55827
     11   2023-11-30   56281
     12   2023-12-31   56436
2024 1    2024-01-31   56064
     2    2024-02-29   55850
     3    2024-03-31   54195
     4    2024-04-30   53853
     5    2024-05-31   54114
     6    2024-06-30   54099
     7    2024-07-31   54061
     8    2024-08-31   54460
     9    2024-09-30   54524
     10   2024-10-31   54526
     11   2024-11-30   54703
     12   2024-12-31   54531
2025 1    2025-01-31   54629
     2    2025-02-28   54058
     3    2025-03-31   53493
     4    2025-04-30   54134
     5    2025-05-31   54486
     6    2025-06-30   54755
     7    2025-07-31   54726
     8    2025-08-31   54529
     9    2025-09-30   54871
     10   2025-10-31   55167
     11   2025-11-30   55213
     12   2025-12-31   55692
2026 1    2026-01-31   56192
     2    2026-02-28   56265
     3    2026-03-31   55895
     4    2026-04-30   55171
     5    2026-05-24   54913

In [ ]:
# View all rows to find mistakes
pd.set_option('display.max_rows', None)

# Create a dataframe showing the date when maximum numbers occurred
merged = pd.merge(df_adults, grouped_adults, on="Adults", how="right")
merged = merged.sort_values(by=["Date_x"])
merged

       Date_x  Adults     Date_y
0  2021-03-07   35232 2021-03-31
1  2021-04-01   34471 2021-04-30
2  2021-05-05   33638 2021-05-31
3  2021-06-01   32826 2021-06-30
4  2021-07-01   31326 2021-07-31
16 2021-07-09   30943 2022-04-30
17 2021-07-16   30943 2022-04-30
5  2021-08-10   30813 2021-08-31
6  2021-09-27   30827 2021-09-30
18 2021-10-05   30943 2022-04-30
7  2021-10-28   31220 2021-10-31
9  2021-11-04   31285 2021-11-30
11 2021-12-03   30872 2022-01-31
19 2021-12-05   30943 2022-04-30
10 2021-12-13   31084 2021-12-31
14 2022-01-25   30802 2022-03-31
12 2022-01-27   30872 2022-01-31
13 2022-02-27   30828 2022-02-28
15 2022-03-09   30802 2022-03-31
20 2022-04-28   30943 2022-04-30
21 2022-05-25   31095 2022-05-31
8  2022-06-02   31220 2021-10-31
22 2022-06-30   31755 2022-06-30
23 2022-07-31   33270 2022-07-31
24 2022-08-31   35712 2022-08-31
25 2022-09-30   40327 2022-09-30
26 2022-10-24   43176 2022-10-31
27 2022-11-21   43277 2022-11-30
28 2022-12-30   44613 2022-12-31
29 2023-01-31   47572 2023-01-31
30 2023-02-04   47980 2023-02-28
31 2023-03-30   49269 2023-03-31
32 2023-04-30   51776 2023-04-30
33 2023-05-20   54505 2023-05-31
51 2023-05-21   54460 2024-08-31
35 2023-06-01   54236 2023-06-30
61 2023-07-03   53493 2025-03-31
36 2023-07-27   53977 2023-07-31
37 2023-08-14   54065 2023-08-31
38 2023-09-27   53584 2023-09-30
40 2023-10-30   55827 2023-10-31
44 2023-11-03   55850 2024-02-29
41 2023-11-13   56281 2023-11-30
76 2023-11-29   56192 2026-01-31
42 2023-12-12   56436 2023-12-31
43 2024-01-11   56064 2024-01-31
45 2024-02-06   55850 2024-02-29
55 2024-02-24   54703 2024-11-30
46 2024-03-01   54195 2024-03-31
62 2024-03-23   53493 2025-03-31
47 2024-04-30   53853 2024-04-30
48 2024-05-09   54114 2024-05-31
49 2024-06-24   54099 2024-06-30
50 2024-07-01   54061 2024-07-31
52 2024-08-22   54460 2024-08-31
53 2024-09-03   54524 2024-09-30
65 2024-09-27   54134 2025-04-30
54 2024-10-15   54526 2024-10-31
56 2024-11-14   54703 2024-11-30
34 2024-11-27   54505 2023-05-31
57 2024-12-01   54531 2024-12-31
58 2025-01-21   54629 2025-01-31
60 2025-02-02   54058 2025-02-28
39 2025-02-14   53584 2023-09-30
63 2025-02-15   53493 2025-03-31
64 2025-03-02   53493 2025-03-31
66 2025-04-28   54134 2025-04-30
67 2025-05-28   54486 2025-05-31
68 2025-06-19   54755 2025-06-30
70 2025-07-01   54726 2025-07-31
71 2025-08-25   54529 2025-08-31
59 2025-09-08   54629 2025-01-31
69 2025-09-17   54755 2025-06-30
72 2025-09-30   54871 2025-09-30
73 2025-10-21   55167 2025-10-31
74 2025-11-28   55213 2025-11-30
75 2025-12-15   55692 2025-12-31
77 2026-01-25   56192 2026-01-31
78 2026-01-31   56192 2026-01-31
79 2026-02-08   56265 2026-02-28
80 2026-03-02   55895 2026-03-31
81 2026-04-13   55171 2026-04-30
82 2026-05-04   54913 2026-05-24